"""add body_html

Revision ID: 3f1f9ac54158
Revises: 
Create Date: 2019-06-10 15:58:49.612941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1f9ac54158'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'body_html',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text('None'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'body_html',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text('None'))
    # ### end Alembic commands ###
